version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: decp_rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: decp_api_gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    environment:
      USER_SERVICE_URL: http://user-service:3001
      CONTENT_SERVICE_URL: http://content-service:3002
      NOTIFICATION_SERVICE_URL: http://notification-service:3003
      CHAT_SERVICE_URL: http://chat-service:3004
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - user-service
      - content-service
      - notification-service
      - chat-service

  user-service:
    build: ./user-service
    container_name: decp_user_service
    ports:
      - "3001:3001"
    env_file: ./user-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  content-service:
    build: ./content-service
    container_name: decp_content_service
    ports:
      - "3002:3002"
    env_file: ./content-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: decp_notification_service
    ports:
      - "3003:3003"
    env_file: ./notification-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  chat-service:
    build: ./chat-service
    container_name: decp_chat_service
    ports:
      - "3004:3004"
    env_file: ./chat-service/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  decp-web-app:
    build: ./decp-web-app
    container_name: decp_frontend
    ports:
      - "5173:80"

volumes:
  rabbitmq_data:
